// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.demo.mmo.mmo_server.protocals;

public final class Login {
  private Login() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CS_101OrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.demo.mmo.mmo_server.protocals.CS_101)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string account = 2;</code>
     */
    java.lang.String getAccount();
    /**
     * <code>optional string account = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();
  }
  /**
   * Protobuf type {@code com.demo.mmo.mmo_server.protocals.CS_101}
   */
  public  static final class CS_101 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.demo.mmo.mmo_server.protocals.CS_101)
      CS_101OrBuilder {
    // Use CS_101.newBuilder() to construct.
    private CS_101(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CS_101() {
      name_ = "";
      account_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CS_101(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              account_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_CS_101_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_CS_101_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.mmo.mmo_server.protocals.Login.CS_101.class, com.demo.mmo.mmo_server.protocals.Login.CS_101.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNT_FIELD_NUMBER = 2;
    private volatile java.lang.Object account_;
    /**
     * <code>optional string account = 2;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <code>optional string account = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getAccountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, account_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getAccountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, account_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.mmo.mmo_server.protocals.Login.CS_101)) {
        return super.equals(obj);
      }
      com.demo.mmo.mmo_server.protocals.Login.CS_101 other = (com.demo.mmo.mmo_server.protocals.Login.CS_101) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getAccount()
          .equals(other.getAccount());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.mmo.mmo_server.protocals.Login.CS_101 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.CS_101 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.CS_101 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.CS_101 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.CS_101 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.CS_101 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.CS_101 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.CS_101 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.CS_101 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.CS_101 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.mmo.mmo_server.protocals.Login.CS_101 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.demo.mmo.mmo_server.protocals.CS_101}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.demo.mmo.mmo_server.protocals.CS_101)
        com.demo.mmo.mmo_server.protocals.Login.CS_101OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_CS_101_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_CS_101_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.mmo.mmo_server.protocals.Login.CS_101.class, com.demo.mmo.mmo_server.protocals.Login.CS_101.Builder.class);
      }

      // Construct using com.demo.mmo.mmo_server.protocals.Login.CS_101.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        account_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_CS_101_descriptor;
      }

      public com.demo.mmo.mmo_server.protocals.Login.CS_101 getDefaultInstanceForType() {
        return com.demo.mmo.mmo_server.protocals.Login.CS_101.getDefaultInstance();
      }

      public com.demo.mmo.mmo_server.protocals.Login.CS_101 build() {
        com.demo.mmo.mmo_server.protocals.Login.CS_101 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.demo.mmo.mmo_server.protocals.Login.CS_101 buildPartial() {
        com.demo.mmo.mmo_server.protocals.Login.CS_101 result = new com.demo.mmo.mmo_server.protocals.Login.CS_101(this);
        result.name_ = name_;
        result.account_ = account_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.mmo.mmo_server.protocals.Login.CS_101) {
          return mergeFrom((com.demo.mmo.mmo_server.protocals.Login.CS_101)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.mmo.mmo_server.protocals.Login.CS_101 other) {
        if (other == com.demo.mmo.mmo_server.protocals.Login.CS_101.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.demo.mmo.mmo_server.protocals.Login.CS_101 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.mmo.mmo_server.protocals.Login.CS_101) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <code>optional string account = 2;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string account = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string account = 2;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 2;</code>
       */
      public Builder clearAccount() {
        
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 2;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        account_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.demo.mmo.mmo_server.protocals.CS_101)
    }

    // @@protoc_insertion_point(class_scope:com.demo.mmo.mmo_server.protocals.CS_101)
    private static final com.demo.mmo.mmo_server.protocals.Login.CS_101 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.mmo.mmo_server.protocals.Login.CS_101();
    }

    public static com.demo.mmo.mmo_server.protocals.Login.CS_101 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CS_101>
        PARSER = new com.google.protobuf.AbstractParser<CS_101>() {
      public CS_101 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CS_101(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CS_101> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CS_101> getParserForType() {
      return PARSER;
    }

    public com.demo.mmo.mmo_server.protocals.Login.CS_101 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SC_101OrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.demo.mmo.mmo_server.protocals.SC_101)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool success = 1;</code>
     */
    boolean getSuccess();

    /**
     * <code>optional sint32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>optional sint32 sex = 3;</code>
     */
    int getSex();

    /**
     * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
     */
    java.util.List<com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate> 
        getClassmatesList();
    /**
     * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
     */
    com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate getClassmates(int index);
    /**
     * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
     */
    int getClassmatesCount();
    /**
     * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
     */
    java.util.List<? extends com.demo.mmo.mmo_server.protocals.Login.SC_101.ClassmateOrBuilder> 
        getClassmatesOrBuilderList();
    /**
     * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
     */
    com.demo.mmo.mmo_server.protocals.Login.SC_101.ClassmateOrBuilder getClassmatesOrBuilder(
        int index);

    /**
     * <code>map&lt;string, string&gt; schoolMap = 5;</code>
     */
    int getSchoolMapCount();
    /**
     * <code>map&lt;string, string&gt; schoolMap = 5;</code>
     */
    boolean containsSchoolMap(
        java.lang.String key);
    /**
     * Use {@link #getSchoolMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getSchoolMap();
    /**
     * <code>map&lt;string, string&gt; schoolMap = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getSchoolMapMap();
    /**
     * <code>map&lt;string, string&gt; schoolMap = 5;</code>
     */

    java.lang.String getSchoolMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; schoolMap = 5;</code>
     */

    java.lang.String getSchoolMapOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.demo.mmo.mmo_server.protocals.SC_101}
   */
  public  static final class SC_101 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.demo.mmo.mmo_server.protocals.SC_101)
      SC_101OrBuilder {
    // Use SC_101.newBuilder() to construct.
    private SC_101(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SC_101() {
      success_ = false;
      age_ = 0;
      sex_ = 0;
      classmates_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SC_101(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 16: {

              age_ = input.readSInt32();
              break;
            }
            case 24: {

              sex_ = input.readSInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                classmates_ = new java.util.ArrayList<com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate>();
                mutable_bitField0_ |= 0x00000008;
              }
              classmates_.add(
                  input.readMessage(com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.parser(), extensionRegistry));
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                schoolMap_ = com.google.protobuf.MapField.newMapField(
                    SchoolMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              schoolMap = input.readMessage(
                  SchoolMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              schoolMap_.getMutableMap().put(schoolMap.getKey(), schoolMap.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          classmates_ = java.util.Collections.unmodifiableList(classmates_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_SC_101_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetSchoolMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_SC_101_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.mmo.mmo_server.protocals.Login.SC_101.class, com.demo.mmo.mmo_server.protocals.Login.SC_101.Builder.class);
    }

    public interface ClassmateOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.demo.mmo.mmo_server.protocals.SC_101.Classmate)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>optional string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>optional int32 sex = 2;</code>
       */
      int getSex();

      /**
       * <code>optional int32 age = 3;</code>
       */
      int getAge();
    }
    /**
     * Protobuf type {@code com.demo.mmo.mmo_server.protocals.SC_101.Classmate}
     */
    public  static final class Classmate extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.demo.mmo.mmo_server.protocals.SC_101.Classmate)
        ClassmateOrBuilder {
      // Use Classmate.newBuilder() to construct.
      private Classmate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Classmate() {
        name_ = "";
        sex_ = 0;
        age_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Classmate(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 16: {

                sex_ = input.readInt32();
                break;
              }
              case 24: {

                age_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_SC_101_Classmate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_SC_101_Classmate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.class, com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SEX_FIELD_NUMBER = 2;
      private int sex_;
      /**
       * <code>optional int32 sex = 2;</code>
       */
      public int getSex() {
        return sex_;
      }

      public static final int AGE_FIELD_NUMBER = 3;
      private int age_;
      /**
       * <code>optional int32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if (sex_ != 0) {
          output.writeInt32(2, sex_);
        }
        if (age_ != 0) {
          output.writeInt32(3, age_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if (sex_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, sex_);
        }
        if (age_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, age_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate)) {
          return super.equals(obj);
        }
        com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate other = (com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate) obj;

        boolean result = true;
        result = result && getName()
            .equals(other.getName());
        result = result && (getSex()
            == other.getSex());
        result = result && (getAge()
            == other.getAge());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + SEX_FIELD_NUMBER;
        hash = (53 * hash) + getSex();
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.demo.mmo.mmo_server.protocals.SC_101.Classmate}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.demo.mmo.mmo_server.protocals.SC_101.Classmate)
          com.demo.mmo.mmo_server.protocals.Login.SC_101.ClassmateOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_SC_101_Classmate_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_SC_101_Classmate_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.class, com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.Builder.class);
        }

        // Construct using com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          name_ = "";

          sex_ = 0;

          age_ = 0;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_SC_101_Classmate_descriptor;
        }

        public com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate getDefaultInstanceForType() {
          return com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.getDefaultInstance();
        }

        public com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate build() {
          com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate buildPartial() {
          com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate result = new com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate(this);
          result.name_ = name_;
          result.sex_ = sex_;
          result.age_ = age_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate) {
            return mergeFrom((com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate other) {
          if (other == com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (other.getSex() != 0) {
            setSex(other.getSex());
          }
          if (other.getAge() != 0) {
            setAge(other.getAge());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>optional string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private int sex_ ;
        /**
         * <code>optional int32 sex = 2;</code>
         */
        public int getSex() {
          return sex_;
        }
        /**
         * <code>optional int32 sex = 2;</code>
         */
        public Builder setSex(int value) {
          
          sex_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 sex = 2;</code>
         */
        public Builder clearSex() {
          
          sex_ = 0;
          onChanged();
          return this;
        }

        private int age_ ;
        /**
         * <code>optional int32 age = 3;</code>
         */
        public int getAge() {
          return age_;
        }
        /**
         * <code>optional int32 age = 3;</code>
         */
        public Builder setAge(int value) {
          
          age_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 age = 3;</code>
         */
        public Builder clearAge() {
          
          age_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:com.demo.mmo.mmo_server.protocals.SC_101.Classmate)
      }

      // @@protoc_insertion_point(class_scope:com.demo.mmo.mmo_server.protocals.SC_101.Classmate)
      private static final com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate();
      }

      public static com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Classmate>
          PARSER = new com.google.protobuf.AbstractParser<Classmate>() {
        public Classmate parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Classmate(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Classmate> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Classmate> getParserForType() {
        return PARSER;
      }

      public com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>optional bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional sint32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private int sex_;
    /**
     * <code>optional sint32 sex = 3;</code>
     */
    public int getSex() {
      return sex_;
    }

    public static final int CLASSMATES_FIELD_NUMBER = 4;
    private java.util.List<com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate> classmates_;
    /**
     * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
     */
    public java.util.List<com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate> getClassmatesList() {
      return classmates_;
    }
    /**
     * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
     */
    public java.util.List<? extends com.demo.mmo.mmo_server.protocals.Login.SC_101.ClassmateOrBuilder> 
        getClassmatesOrBuilderList() {
      return classmates_;
    }
    /**
     * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
     */
    public int getClassmatesCount() {
      return classmates_.size();
    }
    /**
     * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
     */
    public com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate getClassmates(int index) {
      return classmates_.get(index);
    }
    /**
     * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
     */
    public com.demo.mmo.mmo_server.protocals.Login.SC_101.ClassmateOrBuilder getClassmatesOrBuilder(
        int index) {
      return classmates_.get(index);
    }

    public static final int SCHOOLMAP_FIELD_NUMBER = 5;
    private static final class SchoolMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_SC_101_SchoolMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> schoolMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetSchoolMap() {
      if (schoolMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SchoolMapDefaultEntryHolder.defaultEntry);
      }
      return schoolMap_;
    }

    public int getSchoolMapCount() {
      return internalGetSchoolMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; schoolMap = 5;</code>
     */

    public boolean containsSchoolMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetSchoolMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSchoolMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getSchoolMap() {
      return getSchoolMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; schoolMap = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getSchoolMapMap() {
      return internalGetSchoolMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; schoolMap = 5;</code>
     */

    public java.lang.String getSchoolMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSchoolMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; schoolMap = 5;</code>
     */

    public java.lang.String getSchoolMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSchoolMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (age_ != 0) {
        output.writeSInt32(2, age_);
      }
      if (sex_ != 0) {
        output.writeSInt32(3, sex_);
      }
      for (int i = 0; i < classmates_.size(); i++) {
        output.writeMessage(4, classmates_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetSchoolMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        schoolMap = SchoolMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(5, schoolMap);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, age_);
      }
      if (sex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, sex_);
      }
      for (int i = 0; i < classmates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, classmates_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetSchoolMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        schoolMap = SchoolMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, schoolMap);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.mmo.mmo_server.protocals.Login.SC_101)) {
        return super.equals(obj);
      }
      com.demo.mmo.mmo_server.protocals.Login.SC_101 other = (com.demo.mmo.mmo_server.protocals.Login.SC_101) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && (getAge()
          == other.getAge());
      result = result && (getSex()
          == other.getSex());
      result = result && getClassmatesList()
          .equals(other.getClassmatesList());
      result = result && internalGetSchoolMap().equals(
          other.internalGetSchoolMap());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex();
      if (getClassmatesCount() > 0) {
        hash = (37 * hash) + CLASSMATES_FIELD_NUMBER;
        hash = (53 * hash) + getClassmatesList().hashCode();
      }
      if (!internalGetSchoolMap().getMap().isEmpty()) {
        hash = (37 * hash) + SCHOOLMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetSchoolMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.mmo.mmo_server.protocals.Login.SC_101 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.SC_101 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.SC_101 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.SC_101 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.SC_101 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.SC_101 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.SC_101 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.SC_101 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.SC_101 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.Login.SC_101 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.mmo.mmo_server.protocals.Login.SC_101 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.demo.mmo.mmo_server.protocals.SC_101}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.demo.mmo.mmo_server.protocals.SC_101)
        com.demo.mmo.mmo_server.protocals.Login.SC_101OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_SC_101_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetSchoolMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableSchoolMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_SC_101_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.mmo.mmo_server.protocals.Login.SC_101.class, com.demo.mmo.mmo_server.protocals.Login.SC_101.Builder.class);
      }

      // Construct using com.demo.mmo.mmo_server.protocals.Login.SC_101.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getClassmatesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;

        age_ = 0;

        sex_ = 0;

        if (classmatesBuilder_ == null) {
          classmates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          classmatesBuilder_.clear();
        }
        internalGetMutableSchoolMap().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.mmo.mmo_server.protocals.Login.internal_static_com_demo_mmo_mmo_server_protocals_SC_101_descriptor;
      }

      public com.demo.mmo.mmo_server.protocals.Login.SC_101 getDefaultInstanceForType() {
        return com.demo.mmo.mmo_server.protocals.Login.SC_101.getDefaultInstance();
      }

      public com.demo.mmo.mmo_server.protocals.Login.SC_101 build() {
        com.demo.mmo.mmo_server.protocals.Login.SC_101 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.demo.mmo.mmo_server.protocals.Login.SC_101 buildPartial() {
        com.demo.mmo.mmo_server.protocals.Login.SC_101 result = new com.demo.mmo.mmo_server.protocals.Login.SC_101(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.success_ = success_;
        result.age_ = age_;
        result.sex_ = sex_;
        if (classmatesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            classmates_ = java.util.Collections.unmodifiableList(classmates_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.classmates_ = classmates_;
        } else {
          result.classmates_ = classmatesBuilder_.build();
        }
        result.schoolMap_ = internalGetSchoolMap();
        result.schoolMap_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.mmo.mmo_server.protocals.Login.SC_101) {
          return mergeFrom((com.demo.mmo.mmo_server.protocals.Login.SC_101)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.mmo.mmo_server.protocals.Login.SC_101 other) {
        if (other == com.demo.mmo.mmo_server.protocals.Login.SC_101.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getSex() != 0) {
          setSex(other.getSex());
        }
        if (classmatesBuilder_ == null) {
          if (!other.classmates_.isEmpty()) {
            if (classmates_.isEmpty()) {
              classmates_ = other.classmates_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureClassmatesIsMutable();
              classmates_.addAll(other.classmates_);
            }
            onChanged();
          }
        } else {
          if (!other.classmates_.isEmpty()) {
            if (classmatesBuilder_.isEmpty()) {
              classmatesBuilder_.dispose();
              classmatesBuilder_ = null;
              classmates_ = other.classmates_;
              bitField0_ = (bitField0_ & ~0x00000008);
              classmatesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getClassmatesFieldBuilder() : null;
            } else {
              classmatesBuilder_.addAllMessages(other.classmates_);
            }
          }
        }
        internalGetMutableSchoolMap().mergeFrom(
            other.internalGetSchoolMap());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.demo.mmo.mmo_server.protocals.Login.SC_101 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.mmo.mmo_server.protocals.Login.SC_101) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>optional bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional sint32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional sint32 age = 2;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private int sex_ ;
      /**
       * <code>optional sint32 sex = 3;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>optional sint32 sex = 3;</code>
       */
      public Builder setSex(int value) {
        
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 sex = 3;</code>
       */
      public Builder clearSex() {
        
        sex_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate> classmates_ =
        java.util.Collections.emptyList();
      private void ensureClassmatesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          classmates_ = new java.util.ArrayList<com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate>(classmates_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate, com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.Builder, com.demo.mmo.mmo_server.protocals.Login.SC_101.ClassmateOrBuilder> classmatesBuilder_;

      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public java.util.List<com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate> getClassmatesList() {
        if (classmatesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(classmates_);
        } else {
          return classmatesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public int getClassmatesCount() {
        if (classmatesBuilder_ == null) {
          return classmates_.size();
        } else {
          return classmatesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate getClassmates(int index) {
        if (classmatesBuilder_ == null) {
          return classmates_.get(index);
        } else {
          return classmatesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public Builder setClassmates(
          int index, com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate value) {
        if (classmatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClassmatesIsMutable();
          classmates_.set(index, value);
          onChanged();
        } else {
          classmatesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public Builder setClassmates(
          int index, com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.Builder builderForValue) {
        if (classmatesBuilder_ == null) {
          ensureClassmatesIsMutable();
          classmates_.set(index, builderForValue.build());
          onChanged();
        } else {
          classmatesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public Builder addClassmates(com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate value) {
        if (classmatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClassmatesIsMutable();
          classmates_.add(value);
          onChanged();
        } else {
          classmatesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public Builder addClassmates(
          int index, com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate value) {
        if (classmatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClassmatesIsMutable();
          classmates_.add(index, value);
          onChanged();
        } else {
          classmatesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public Builder addClassmates(
          com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.Builder builderForValue) {
        if (classmatesBuilder_ == null) {
          ensureClassmatesIsMutable();
          classmates_.add(builderForValue.build());
          onChanged();
        } else {
          classmatesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public Builder addClassmates(
          int index, com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.Builder builderForValue) {
        if (classmatesBuilder_ == null) {
          ensureClassmatesIsMutable();
          classmates_.add(index, builderForValue.build());
          onChanged();
        } else {
          classmatesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public Builder addAllClassmates(
          java.lang.Iterable<? extends com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate> values) {
        if (classmatesBuilder_ == null) {
          ensureClassmatesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, classmates_);
          onChanged();
        } else {
          classmatesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public Builder clearClassmates() {
        if (classmatesBuilder_ == null) {
          classmates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          classmatesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public Builder removeClassmates(int index) {
        if (classmatesBuilder_ == null) {
          ensureClassmatesIsMutable();
          classmates_.remove(index);
          onChanged();
        } else {
          classmatesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.Builder getClassmatesBuilder(
          int index) {
        return getClassmatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public com.demo.mmo.mmo_server.protocals.Login.SC_101.ClassmateOrBuilder getClassmatesOrBuilder(
          int index) {
        if (classmatesBuilder_ == null) {
          return classmates_.get(index);  } else {
          return classmatesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public java.util.List<? extends com.demo.mmo.mmo_server.protocals.Login.SC_101.ClassmateOrBuilder> 
           getClassmatesOrBuilderList() {
        if (classmatesBuilder_ != null) {
          return classmatesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(classmates_);
        }
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.Builder addClassmatesBuilder() {
        return getClassmatesFieldBuilder().addBuilder(
            com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.getDefaultInstance());
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.Builder addClassmatesBuilder(
          int index) {
        return getClassmatesFieldBuilder().addBuilder(
            index, com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.getDefaultInstance());
      }
      /**
       * <code>repeated .com.demo.mmo.mmo_server.protocals.SC_101.Classmate classmates = 4;</code>
       */
      public java.util.List<com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.Builder> 
           getClassmatesBuilderList() {
        return getClassmatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate, com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.Builder, com.demo.mmo.mmo_server.protocals.Login.SC_101.ClassmateOrBuilder> 
          getClassmatesFieldBuilder() {
        if (classmatesBuilder_ == null) {
          classmatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate, com.demo.mmo.mmo_server.protocals.Login.SC_101.Classmate.Builder, com.demo.mmo.mmo_server.protocals.Login.SC_101.ClassmateOrBuilder>(
                  classmates_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          classmates_ = null;
        }
        return classmatesBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> schoolMap_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetSchoolMap() {
        if (schoolMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              SchoolMapDefaultEntryHolder.defaultEntry);
        }
        return schoolMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableSchoolMap() {
        onChanged();;
        if (schoolMap_ == null) {
          schoolMap_ = com.google.protobuf.MapField.newMapField(
              SchoolMapDefaultEntryHolder.defaultEntry);
        }
        if (!schoolMap_.isMutable()) {
          schoolMap_ = schoolMap_.copy();
        }
        return schoolMap_;
      }

      public int getSchoolMapCount() {
        return internalGetSchoolMap().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; schoolMap = 5;</code>
       */

      public boolean containsSchoolMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetSchoolMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getSchoolMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getSchoolMap() {
        return getSchoolMapMap();
      }
      /**
       * <code>map&lt;string, string&gt; schoolMap = 5;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getSchoolMapMap() {
        return internalGetSchoolMap().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; schoolMap = 5;</code>
       */

      public java.lang.String getSchoolMapOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetSchoolMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; schoolMap = 5;</code>
       */

      public java.lang.String getSchoolMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetSchoolMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearSchoolMap() {
        getMutableSchoolMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; schoolMap = 5;</code>
       */

      public Builder removeSchoolMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableSchoolMap().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableSchoolMap() {
        return internalGetMutableSchoolMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; schoolMap = 5;</code>
       */
      public Builder putSchoolMap(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableSchoolMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; schoolMap = 5;</code>
       */

      public Builder putAllSchoolMap(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableSchoolMap().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.demo.mmo.mmo_server.protocals.SC_101)
    }

    // @@protoc_insertion_point(class_scope:com.demo.mmo.mmo_server.protocals.SC_101)
    private static final com.demo.mmo.mmo_server.protocals.Login.SC_101 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.mmo.mmo_server.protocals.Login.SC_101();
    }

    public static com.demo.mmo.mmo_server.protocals.Login.SC_101 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SC_101>
        PARSER = new com.google.protobuf.AbstractParser<SC_101>() {
      public SC_101 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SC_101(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SC_101> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SC_101> getParserForType() {
      return PARSER;
    }

    public com.demo.mmo.mmo_server.protocals.Login.SC_101 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_mmo_mmo_server_protocals_CS_101_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_mmo_mmo_server_protocals_CS_101_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_mmo_mmo_server_protocals_SC_101_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_mmo_mmo_server_protocals_SC_101_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_mmo_mmo_server_protocals_SC_101_Classmate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_mmo_mmo_server_protocals_SC_101_Classmate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_mmo_mmo_server_protocals_SC_101_SchoolMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_mmo_mmo_server_protocals_SC_101_SchoolMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013login.proto\022!com.demo.mmo.mmo_server.p" +
      "rotocals\"\'\n\006CS_101\022\014\n\004name\030\001 \001(\t\022\017\n\007acco" +
      "unt\030\002 \001(\t\"\260\002\n\006SC_101\022\017\n\007success\030\001 \001(\010\022\013\n" +
      "\003age\030\002 \001(\021\022\013\n\003sex\030\003 \001(\021\022G\n\nclassmates\030\004 " +
      "\003(\01323.com.demo.mmo.mmo_server.protocals." +
      "SC_101.Classmate\022K\n\tschoolMap\030\005 \003(\01328.co" +
      "m.demo.mmo.mmo_server.protocals.SC_101.S" +
      "choolMapEntry\0323\n\tClassmate\022\014\n\004name\030\001 \001(\t" +
      "\022\013\n\003sex\030\002 \001(\005\022\013\n\003age\030\003 \001(\005\0320\n\016SchoolMapE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001b\006pr",
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_demo_mmo_mmo_server_protocals_CS_101_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_demo_mmo_mmo_server_protocals_CS_101_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_mmo_mmo_server_protocals_CS_101_descriptor,
        new java.lang.String[] { "Name", "Account", });
    internal_static_com_demo_mmo_mmo_server_protocals_SC_101_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_demo_mmo_mmo_server_protocals_SC_101_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_mmo_mmo_server_protocals_SC_101_descriptor,
        new java.lang.String[] { "Success", "Age", "Sex", "Classmates", "SchoolMap", });
    internal_static_com_demo_mmo_mmo_server_protocals_SC_101_Classmate_descriptor =
      internal_static_com_demo_mmo_mmo_server_protocals_SC_101_descriptor.getNestedTypes().get(0);
    internal_static_com_demo_mmo_mmo_server_protocals_SC_101_Classmate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_mmo_mmo_server_protocals_SC_101_Classmate_descriptor,
        new java.lang.String[] { "Name", "Sex", "Age", });
    internal_static_com_demo_mmo_mmo_server_protocals_SC_101_SchoolMapEntry_descriptor =
      internal_static_com_demo_mmo_mmo_server_protocals_SC_101_descriptor.getNestedTypes().get(1);
    internal_static_com_demo_mmo_mmo_server_protocals_SC_101_SchoolMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_mmo_mmo_server_protocals_SC_101_SchoolMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
