// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocal.proto

package com.demo.mmo.mmo_server.protocals;

public final class Protocal {
  private Protocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.demo.mmo.mmo_server.protocals.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 protocal = 1;</code>
     */
    int getProtocal();

    /**
     * <code>optional bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.demo.mmo.mmo_server.protocals.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.demo.mmo.mmo_server.protocals.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      protocal_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              protocal_ = input.readUInt32();
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.mmo.mmo_server.protocals.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.mmo.mmo_server.protocals.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.mmo.mmo_server.protocals.Protocal.Request.class, com.demo.mmo.mmo_server.protocals.Protocal.Request.Builder.class);
    }

    public static final int PROTOCAL_FIELD_NUMBER = 1;
    private int protocal_;
    /**
     * <code>optional uint32 protocal = 1;</code>
     */
    public int getProtocal() {
      return protocal_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (protocal_ != 0) {
        output.writeUInt32(1, protocal_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (protocal_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, protocal_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.mmo.mmo_server.protocals.Protocal.Request)) {
        return super.equals(obj);
      }
      com.demo.mmo.mmo_server.protocals.Protocal.Request other = (com.demo.mmo.mmo_server.protocals.Protocal.Request) obj;

      boolean result = true;
      result = result && (getProtocal()
          == other.getProtocal());
      result = result && getData()
          .equals(other.getData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PROTOCAL_FIELD_NUMBER;
      hash = (53 * hash) + getProtocal();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.mmo.mmo_server.protocals.Protocal.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.mmo.mmo_server.protocals.Protocal.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.demo.mmo.mmo_server.protocals.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.demo.mmo.mmo_server.protocals.Request)
        com.demo.mmo.mmo_server.protocals.Protocal.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.mmo.mmo_server.protocals.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.mmo.mmo_server.protocals.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.mmo.mmo_server.protocals.Protocal.Request.class, com.demo.mmo.mmo_server.protocals.Protocal.Request.Builder.class);
      }

      // Construct using com.demo.mmo.mmo_server.protocals.Protocal.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        protocal_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.mmo.mmo_server.protocals.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_Request_descriptor;
      }

      public com.demo.mmo.mmo_server.protocals.Protocal.Request getDefaultInstanceForType() {
        return com.demo.mmo.mmo_server.protocals.Protocal.Request.getDefaultInstance();
      }

      public com.demo.mmo.mmo_server.protocals.Protocal.Request build() {
        com.demo.mmo.mmo_server.protocals.Protocal.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.demo.mmo.mmo_server.protocals.Protocal.Request buildPartial() {
        com.demo.mmo.mmo_server.protocals.Protocal.Request result = new com.demo.mmo.mmo_server.protocals.Protocal.Request(this);
        result.protocal_ = protocal_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.mmo.mmo_server.protocals.Protocal.Request) {
          return mergeFrom((com.demo.mmo.mmo_server.protocals.Protocal.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.mmo.mmo_server.protocals.Protocal.Request other) {
        if (other == com.demo.mmo.mmo_server.protocals.Protocal.Request.getDefaultInstance()) return this;
        if (other.getProtocal() != 0) {
          setProtocal(other.getProtocal());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.demo.mmo.mmo_server.protocals.Protocal.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.mmo.mmo_server.protocals.Protocal.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int protocal_ ;
      /**
       * <code>optional uint32 protocal = 1;</code>
       */
      public int getProtocal() {
        return protocal_;
      }
      /**
       * <code>optional uint32 protocal = 1;</code>
       */
      public Builder setProtocal(int value) {
        
        protocal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 protocal = 1;</code>
       */
      public Builder clearProtocal() {
        
        protocal_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.demo.mmo.mmo_server.protocals.Request)
    }

    // @@protoc_insertion_point(class_scope:com.demo.mmo.mmo_server.protocals.Request)
    private static final com.demo.mmo.mmo_server.protocals.Protocal.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.mmo.mmo_server.protocals.Protocal.Request();
    }

    public static com.demo.mmo.mmo_server.protocals.Protocal.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public com.demo.mmo.mmo_server.protocals.Protocal.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Data101OrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.demo.mmo.mmo_server.protocals.Data101)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional sint32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>optional sint32 sex = 3;</code>
     */
    int getSex();
  }
  /**
   * Protobuf type {@code com.demo.mmo.mmo_server.protocals.Data101}
   */
  public  static final class Data101 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.demo.mmo.mmo_server.protocals.Data101)
      Data101OrBuilder {
    // Use Data101.newBuilder() to construct.
    private Data101(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data101() {
      name_ = "";
      age_ = 0;
      sex_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Data101(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readSInt32();
              break;
            }
            case 24: {

              sex_ = input.readSInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.mmo.mmo_server.protocals.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_Data101_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.mmo.mmo_server.protocals.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_Data101_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.mmo.mmo_server.protocals.Protocal.Data101.class, com.demo.mmo.mmo_server.protocals.Protocal.Data101.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional sint32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private int sex_;
    /**
     * <code>optional sint32 sex = 3;</code>
     */
    public int getSex() {
      return sex_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeSInt32(2, age_);
      }
      if (sex_ != 0) {
        output.writeSInt32(3, sex_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, age_);
      }
      if (sex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, sex_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.mmo.mmo_server.protocals.Protocal.Data101)) {
        return super.equals(obj);
      }
      com.demo.mmo.mmo_server.protocals.Protocal.Data101 other = (com.demo.mmo.mmo_server.protocals.Protocal.Data101) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && (getSex()
          == other.getSex());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.mmo.mmo_server.protocals.Protocal.Data101 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Data101 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Data101 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Data101 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Data101 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Data101 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Data101 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Data101 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Data101 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.Protocal.Data101 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.mmo.mmo_server.protocals.Protocal.Data101 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.demo.mmo.mmo_server.protocals.Data101}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.demo.mmo.mmo_server.protocals.Data101)
        com.demo.mmo.mmo_server.protocals.Protocal.Data101OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.mmo.mmo_server.protocals.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_Data101_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.mmo.mmo_server.protocals.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_Data101_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.mmo.mmo_server.protocals.Protocal.Data101.class, com.demo.mmo.mmo_server.protocals.Protocal.Data101.Builder.class);
      }

      // Construct using com.demo.mmo.mmo_server.protocals.Protocal.Data101.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        sex_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.mmo.mmo_server.protocals.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_Data101_descriptor;
      }

      public com.demo.mmo.mmo_server.protocals.Protocal.Data101 getDefaultInstanceForType() {
        return com.demo.mmo.mmo_server.protocals.Protocal.Data101.getDefaultInstance();
      }

      public com.demo.mmo.mmo_server.protocals.Protocal.Data101 build() {
        com.demo.mmo.mmo_server.protocals.Protocal.Data101 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.demo.mmo.mmo_server.protocals.Protocal.Data101 buildPartial() {
        com.demo.mmo.mmo_server.protocals.Protocal.Data101 result = new com.demo.mmo.mmo_server.protocals.Protocal.Data101(this);
        result.name_ = name_;
        result.age_ = age_;
        result.sex_ = sex_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.mmo.mmo_server.protocals.Protocal.Data101) {
          return mergeFrom((com.demo.mmo.mmo_server.protocals.Protocal.Data101)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.mmo.mmo_server.protocals.Protocal.Data101 other) {
        if (other == com.demo.mmo.mmo_server.protocals.Protocal.Data101.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getSex() != 0) {
          setSex(other.getSex());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.demo.mmo.mmo_server.protocals.Protocal.Data101 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.mmo.mmo_server.protocals.Protocal.Data101) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional sint32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional sint32 age = 2;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private int sex_ ;
      /**
       * <code>optional sint32 sex = 3;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>optional sint32 sex = 3;</code>
       */
      public Builder setSex(int value) {
        
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 sex = 3;</code>
       */
      public Builder clearSex() {
        
        sex_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.demo.mmo.mmo_server.protocals.Data101)
    }

    // @@protoc_insertion_point(class_scope:com.demo.mmo.mmo_server.protocals.Data101)
    private static final com.demo.mmo.mmo_server.protocals.Protocal.Data101 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.mmo.mmo_server.protocals.Protocal.Data101();
    }

    public static com.demo.mmo.mmo_server.protocals.Protocal.Data101 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data101>
        PARSER = new com.google.protobuf.AbstractParser<Data101>() {
      public Data101 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Data101(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Data101> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data101> getParserForType() {
      return PARSER;
    }

    public com.demo.mmo.mmo_server.protocals.Protocal.Data101 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_mmo_mmo_server_protocals_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_mmo_mmo_server_protocals_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_mmo_mmo_server_protocals_Data101_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_mmo_mmo_server_protocals_Data101_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protocal.proto\022!com.demo.mmo.mmo_serve" +
      "r.protocals\")\n\007Request\022\020\n\010protocal\030\001 \001(\r" +
      "\022\014\n\004data\030\002 \001(\014\"1\n\007Data101\022\014\n\004name\030\001 \001(\t\022" +
      "\013\n\003age\030\002 \001(\021\022\013\n\003sex\030\003 \001(\021b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_demo_mmo_mmo_server_protocals_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_demo_mmo_mmo_server_protocals_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_mmo_mmo_server_protocals_Request_descriptor,
        new java.lang.String[] { "Protocal", "Data", });
    internal_static_com_demo_mmo_mmo_server_protocals_Data101_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_demo_mmo_mmo_server_protocals_Data101_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_mmo_mmo_server_protocals_Data101_descriptor,
        new java.lang.String[] { "Name", "Age", "Sex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
