// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocal.proto

package com.demo.mmo.mmo_server.protocals.base;

public final class Protocal {
  private Protocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.demo.mmo.mmo_server.protocals.base.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional sint32 protocal = 1;</code>
     */
    int getProtocal();

    /**
     * <code>optional bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.demo.mmo.mmo_server.protocals.base.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.demo.mmo.mmo_server.protocals.base.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      protocal_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              protocal_ = input.readSInt32();
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.mmo.mmo_server.protocals.base.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_base_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.mmo.mmo_server.protocals.base.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_base_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.mmo.mmo_server.protocals.base.Protocal.Request.class, com.demo.mmo.mmo_server.protocals.base.Protocal.Request.Builder.class);
    }

    public static final int PROTOCAL_FIELD_NUMBER = 1;
    private int protocal_;
    /**
     * <code>optional sint32 protocal = 1;</code>
     */
    public int getProtocal() {
      return protocal_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (protocal_ != 0) {
        output.writeSInt32(1, protocal_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (protocal_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, protocal_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.mmo.mmo_server.protocals.base.Protocal.Request)) {
        return super.equals(obj);
      }
      com.demo.mmo.mmo_server.protocals.base.Protocal.Request other = (com.demo.mmo.mmo_server.protocals.base.Protocal.Request) obj;

      boolean result = true;
      result = result && (getProtocal()
          == other.getProtocal());
      result = result && getData()
          .equals(other.getData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PROTOCAL_FIELD_NUMBER;
      hash = (53 * hash) + getProtocal();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.mmo.mmo_server.protocals.base.Protocal.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.demo.mmo.mmo_server.protocals.base.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.demo.mmo.mmo_server.protocals.base.Request)
        com.demo.mmo.mmo_server.protocals.base.Protocal.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.mmo.mmo_server.protocals.base.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_base_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.mmo.mmo_server.protocals.base.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_base_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.mmo.mmo_server.protocals.base.Protocal.Request.class, com.demo.mmo.mmo_server.protocals.base.Protocal.Request.Builder.class);
      }

      // Construct using com.demo.mmo.mmo_server.protocals.base.Protocal.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        protocal_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.mmo.mmo_server.protocals.base.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_base_Request_descriptor;
      }

      public com.demo.mmo.mmo_server.protocals.base.Protocal.Request getDefaultInstanceForType() {
        return com.demo.mmo.mmo_server.protocals.base.Protocal.Request.getDefaultInstance();
      }

      public com.demo.mmo.mmo_server.protocals.base.Protocal.Request build() {
        com.demo.mmo.mmo_server.protocals.base.Protocal.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.demo.mmo.mmo_server.protocals.base.Protocal.Request buildPartial() {
        com.demo.mmo.mmo_server.protocals.base.Protocal.Request result = new com.demo.mmo.mmo_server.protocals.base.Protocal.Request(this);
        result.protocal_ = protocal_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.mmo.mmo_server.protocals.base.Protocal.Request) {
          return mergeFrom((com.demo.mmo.mmo_server.protocals.base.Protocal.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.mmo.mmo_server.protocals.base.Protocal.Request other) {
        if (other == com.demo.mmo.mmo_server.protocals.base.Protocal.Request.getDefaultInstance()) return this;
        if (other.getProtocal() != 0) {
          setProtocal(other.getProtocal());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.demo.mmo.mmo_server.protocals.base.Protocal.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.mmo.mmo_server.protocals.base.Protocal.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int protocal_ ;
      /**
       * <code>optional sint32 protocal = 1;</code>
       */
      public int getProtocal() {
        return protocal_;
      }
      /**
       * <code>optional sint32 protocal = 1;</code>
       */
      public Builder setProtocal(int value) {
        
        protocal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 protocal = 1;</code>
       */
      public Builder clearProtocal() {
        
        protocal_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.demo.mmo.mmo_server.protocals.base.Request)
    }

    // @@protoc_insertion_point(class_scope:com.demo.mmo.mmo_server.protocals.base.Request)
    private static final com.demo.mmo.mmo_server.protocals.base.Protocal.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.mmo.mmo_server.protocals.base.Protocal.Request();
    }

    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public com.demo.mmo.mmo_server.protocals.base.Protocal.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.demo.mmo.mmo_server.protocals.base.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional sint32 protocal = 1;</code>
     */
    int getProtocal();

    /**
     * <code>optional bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.demo.mmo.mmo_server.protocals.base.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.demo.mmo.mmo_server.protocals.base.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      protocal_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              protocal_ = input.readSInt32();
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.mmo.mmo_server.protocals.base.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_base_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.mmo.mmo_server.protocals.base.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_base_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.mmo.mmo_server.protocals.base.Protocal.Response.class, com.demo.mmo.mmo_server.protocals.base.Protocal.Response.Builder.class);
    }

    public static final int PROTOCAL_FIELD_NUMBER = 1;
    private int protocal_;
    /**
     * <code>optional sint32 protocal = 1;</code>
     */
    public int getProtocal() {
      return protocal_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (protocal_ != 0) {
        output.writeSInt32(1, protocal_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (protocal_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, protocal_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.mmo.mmo_server.protocals.base.Protocal.Response)) {
        return super.equals(obj);
      }
      com.demo.mmo.mmo_server.protocals.base.Protocal.Response other = (com.demo.mmo.mmo_server.protocals.base.Protocal.Response) obj;

      boolean result = true;
      result = result && (getProtocal()
          == other.getProtocal());
      result = result && getData()
          .equals(other.getData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PROTOCAL_FIELD_NUMBER;
      hash = (53 * hash) + getProtocal();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.mmo.mmo_server.protocals.base.Protocal.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.demo.mmo.mmo_server.protocals.base.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.demo.mmo.mmo_server.protocals.base.Response)
        com.demo.mmo.mmo_server.protocals.base.Protocal.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.mmo.mmo_server.protocals.base.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_base_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.mmo.mmo_server.protocals.base.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_base_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.mmo.mmo_server.protocals.base.Protocal.Response.class, com.demo.mmo.mmo_server.protocals.base.Protocal.Response.Builder.class);
      }

      // Construct using com.demo.mmo.mmo_server.protocals.base.Protocal.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        protocal_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.mmo.mmo_server.protocals.base.Protocal.internal_static_com_demo_mmo_mmo_server_protocals_base_Response_descriptor;
      }

      public com.demo.mmo.mmo_server.protocals.base.Protocal.Response getDefaultInstanceForType() {
        return com.demo.mmo.mmo_server.protocals.base.Protocal.Response.getDefaultInstance();
      }

      public com.demo.mmo.mmo_server.protocals.base.Protocal.Response build() {
        com.demo.mmo.mmo_server.protocals.base.Protocal.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.demo.mmo.mmo_server.protocals.base.Protocal.Response buildPartial() {
        com.demo.mmo.mmo_server.protocals.base.Protocal.Response result = new com.demo.mmo.mmo_server.protocals.base.Protocal.Response(this);
        result.protocal_ = protocal_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.mmo.mmo_server.protocals.base.Protocal.Response) {
          return mergeFrom((com.demo.mmo.mmo_server.protocals.base.Protocal.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.mmo.mmo_server.protocals.base.Protocal.Response other) {
        if (other == com.demo.mmo.mmo_server.protocals.base.Protocal.Response.getDefaultInstance()) return this;
        if (other.getProtocal() != 0) {
          setProtocal(other.getProtocal());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.demo.mmo.mmo_server.protocals.base.Protocal.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.mmo.mmo_server.protocals.base.Protocal.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int protocal_ ;
      /**
       * <code>optional sint32 protocal = 1;</code>
       */
      public int getProtocal() {
        return protocal_;
      }
      /**
       * <code>optional sint32 protocal = 1;</code>
       */
      public Builder setProtocal(int value) {
        
        protocal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 protocal = 1;</code>
       */
      public Builder clearProtocal() {
        
        protocal_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.demo.mmo.mmo_server.protocals.base.Response)
    }

    // @@protoc_insertion_point(class_scope:com.demo.mmo.mmo_server.protocals.base.Response)
    private static final com.demo.mmo.mmo_server.protocals.base.Protocal.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.mmo.mmo_server.protocals.base.Protocal.Response();
    }

    public static com.demo.mmo.mmo_server.protocals.base.Protocal.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public com.demo.mmo.mmo_server.protocals.base.Protocal.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_mmo_mmo_server_protocals_base_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_mmo_mmo_server_protocals_base_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_mmo_mmo_server_protocals_base_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_mmo_mmo_server_protocals_base_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protocal.proto\022&com.demo.mmo.mmo_serve" +
      "r.protocals.base\")\n\007Request\022\020\n\010protocal\030" +
      "\001 \001(\021\022\014\n\004data\030\002 \001(\014\"*\n\010Response\022\020\n\010proto" +
      "cal\030\001 \001(\021\022\014\n\004data\030\002 \001(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_demo_mmo_mmo_server_protocals_base_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_demo_mmo_mmo_server_protocals_base_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_mmo_mmo_server_protocals_base_Request_descriptor,
        new java.lang.String[] { "Protocal", "Data", });
    internal_static_com_demo_mmo_mmo_server_protocals_base_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_demo_mmo_mmo_server_protocals_base_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_mmo_mmo_server_protocals_base_Response_descriptor,
        new java.lang.String[] { "Protocal", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
